/* Seleccionar una a una y ejecutar o seleccionar un bloque entero y ejecutar */

DESCRIBE TIPOS_DPTOS;
DESCRIBE EDIFICIOS;
DESCRIBE DEPARTAMENTOS;
DESCRIBE AULAS;
DESCRIBE AREAS_SABER;
DESCRIBE PROFESORES;
DESCRIBE SECCIONES;
DESCRIBE ASIGNATURAS;
DESCRIBE BLOQUE_HORA;
DESCRIBE DISPONIBILIDAD;
DESCRIBE HOR_CLASES;

SELECT * FROM TIPOS_DPTOS;
SELECT * FROM EDIFICIOS;
SELECT * FROM DEPARTAMENTOS;
SELECT * FROM AULAS;
SELECT * FROM AREAS_SABER;
SELECT * FROM PROFESORES;
SELECT * FROM SECCIONES;
SELECT * FROM ASIGNATURAS;
SELECT * FROM BLOQUE_HORA;
SELECT * FROM DISPONIBILIDAD;
SELECT * FROM HOR_CLASES;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE HOR_CLASES;
TRUNCATE TABLE DISPONIBILIDAD;
TRUNCATE TABLE BLOQUE_HORA;
TRUNCATE TABLE SECCIONES;
TRUNCATE TABLE ASIGNATURAS;
TRUNCATE TABLE PROFESORES;
TRUNCATE TABLE AREAS_SABER;
TRUNCATE TABLE AULAS;
TRUNCATE TABLE DEPARTAMENTOS;
TRUNCATE TABLE EDIFICIOS;
TRUNCATE TABLE TIPOS_DPTOS;
SET FOREIGN_KEY_CHECKS = 1;

DROP TABLE HOR_CLASES;
DROP TABLE DISPONIBILIDAD;
DROP TRIGGER touppercasebloquehora;
DROP TABLE BLOQUE_HORA;
DROP TABLE SECCIONES;
DROP TRIGGER TOUPPERCASEASIG;
DROP TABLE ASIGNATURAS;
DROP TRIGGER TOUPPERCASEPROF;
DROP TABLE PROFESORES;
DROP TABLE AREAS_SABER;
DROP TABLE AULAS;
DROP TABLE DEPARTAMENTOS;
DROP TABLE EDIFICIOS;
DROP TRIGGER touppercasetiposdpto;
DROP TABLE TIPOS_DPTOS;